/**
 * HumanReviewQueue — Refactored with Design System Components
 *
 * Improvements:
 * - PageHero
 * - KpiCard with proper variants
 * - Badge for priority levels
 * - StatusBadge for review status
 * - Modal for review action confirmation
 * - useToast for approve/escalate feedback
 * - Alert for SLA risk warning
 * - Card components
 * - EmptyState for empty queue
 */

import React, { useState } from 'react';
import { Clock3, FileWarning, ShieldCheck, UserCheck, Workflow } from 'lucide-react';
import {
  Alert, Badge, Button, Card, EmptyState, KpiCard,
  Modal, PageHero, SectionHeader, StatusBadge, useToast,
} from './components/index.js';

const reviews = [
  {
    id: 'REV-1042', type: 'Candidate rejection', candidate: 'Meera Shah',    role: 'Operations Manager',
    priority: 'High',     sla: '1h 22m left', slaRisk: true,
    reason: 'AI confidence below threshold + client override requested',       status: 'Open',
  },
  {
    id: 'REV-1041', type: 'Compliance flag',      candidate: 'Farhan Ali',   role: 'Voice Support',
    priority: 'Critical', sla: '42m left',    slaRisk: true,
    reason: 'Public web-data source requires approval before enrichment',      status: 'Open',
  },
  {
    id: 'REV-1039', type: 'Executive assessment', candidate: 'Priya Menon',  role: 'VP Sales',
    priority: 'High',     sla: '3h 10m left', slaRisk: false,
    reason: 'Leadership video evaluation requires human calibration',          status: 'In Review',
  },
  {
    id: 'REV-1037', type: 'Trait question approval', candidate: 'Question Bank', role: 'HR Manager',
    priority: 'Medium',   sla: '8h left',     slaRisk: false,
    reason: 'New confidentiality question set generated by AI',                status: 'Open',
  },
];

const PRIORITY_VARIANT = { Critical: 'danger', High: 'warning', Medium: 'info', Low: 'default' };

export default function HumanReviewQueue() {
  const { toast, ToastContainer } = useToast();
  const [actionModal, setActionModal] = useState(null); // { review, action: 'approve'|'escalate' }
  const [dismissed, setDismissed] = useState(new Set());

  const slaAtRisk = reviews.filter((r) => r.slaRisk).length;

  const activeReviews = reviews.filter((r) => !dismissed.has(r.id));

  function handleAction(review, action) {
    setActionModal({ review, action });
  }

  function confirmAction() {
    const { review, action } = actionModal;
    toast(
      action === 'approve'
        ? `${review.id} approved — candidate outcome recorded with audit trail.`
        : `${review.id} escalated to senior reviewer.`,
      { type: action === 'approve' ? 'success' : 'warning' }
    );
    setDismissed((prev) => new Set([...prev, review.id]));
    setActionModal(null);
  }

  const sidePanelContent = (
    <div style={{ border: '1px solid rgba(52,211,153,.2)', borderRadius: 20, padding: '18px 20px', background: 'rgba(52,211,153,.06)' }}>
      <ShieldCheck size={24} style={{ color: '#34D399', marginBottom: 10 }} />
      <strong style={{ display: 'block', fontSize: 40, fontWeight: 800, color: '#F8FAFC', letterSpacing: -2 }}>100%</strong>
      <span style={{ fontSize: 13, color: '#64748B' }}>high-risk decisions require review</span>
    </div>
  );

  return (
    <section className="page ops-page">
      <ToastContainer />

      <PageHero
        eyebrow="Human-in-the-loop control"
        eyebrowIcon={<UserCheck size={14} />}
        title="Review every high-risk hiring decision before it impacts a candidate."
        subtitle="Premium enterprise hiring cannot be black-box. This queue gives reviewers context, SLA, risk level, evidence, and decision controls for sensitive candidate outcomes."
        sidePanel={sidePanelContent}
        gradient="violet-cyan"
      />

      {slaAtRisk > 0 && (
        <Alert type="error" title={`${slaAtRisk} items at SLA risk`} dismissible style={{ marginBottom: 20 }}>
          Act immediately — these reviews will breach SLA within the hour.
        </Alert>
      )}

      {/* KPI Row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 28 }}>
        <KpiCard label="Open Reviews"     value="34"  sub="12 high priority" variant="danger"  />
        <KpiCard label="SLA Risk"         value="7"   sub="Needs action"     variant="gold"    />
        <KpiCard label="Resolved Today"   value="48"  sub="4h median"        variant="green"   />
        <KpiCard label="Human Overrides"  value="11"  sub="100% audited"     variant="violet"  />
      </div>

      {/* Review queue */}
      <Card variant="glass" header={
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
          <SectionHeader icon={<Workflow />} title="Review Queue" subtitle="Prioritized by risk, SLA, and candidate impact." size="sm" />
          <Button variant="primary" size="sm">Assign Next Review</Button>
        </div>
      }>
        {activeReviews.length === 0 ? (
          <EmptyState
            icon={<ShieldCheck />}
            title="All reviews resolved"
            description="No pending human review items. Great work!"
            size="lg"
          />
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
            {activeReviews.map((item) => (
              <div
                key={item.id}
                style={{
                  display: 'grid',
                  gridTemplateColumns: '160px 1fr auto auto',
                  gap: 16,
                  alignItems: 'flex-start',
                  padding: '18px 0',
                  borderBottom: '1px solid rgba(255,255,255,.07)',
                }}
              >
                {/* ID + type */}
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 4 }}>
                    <FileWarning size={14} style={{ color: '#67E8F9', flexShrink: 0 }} />
                    <strong style={{ fontSize: 13, color: '#67E8F9', fontVariantNumeric: 'tabular-nums' }}>{item.id}</strong>
                  </div>
                  <span style={{ fontSize: 12, color: '#64748B' }}>{item.type}</span>
                </div>

                {/* Content */}
                <div>
                  <strong style={{ display: 'block', fontSize: 14, color: '#F8FAFC', marginBottom: 2 }}>{item.candidate}</strong>
                  <span style={{ fontSize: 12, color: '#94A3B8', display: 'block', marginBottom: 6 }}>{item.role}</span>
                  <p style={{ margin: 0, fontSize: 13, color: '#64748B', lineHeight: 1.5 }}>{item.reason}</p>
                </div>

                {/* Meta */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6, alignItems: 'flex-end', flexShrink: 0 }}>
                  <Badge variant={PRIORITY_VARIANT[item.priority] ?? 'default'} size="sm">{item.priority}</Badge>
                  <span style={{ display: 'flex', alignItems: 'center', gap: 4, fontSize: 12, color: item.slaRisk ? '#FB7185' : '#64748B' }}>
                    <Clock3 size={13} /> {item.sla}
                  </span>
                  <StatusBadge status={item.status} />
                </div>

                {/* Actions */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6, flexShrink: 0 }}>
                  <Button variant="success" size="sm" onClick={() => handleAction(item, 'approve')}>Approve</Button>
                  <Button variant="ghost"   size="sm" onClick={() => handleAction(item, 'escalate')}>Escalate</Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Confirm action modal */}
      <Modal
        open={!!actionModal}
        onClose={() => setActionModal(null)}
        title={actionModal?.action === 'approve' ? 'Confirm Approval' : 'Escalate Review'}
        size="sm"
        footer={
          <div style={{ display: 'flex', gap: 10 }}>
            <Button variant="ghost" size="sm" onClick={() => setActionModal(null)}>Cancel</Button>
            <Button
              variant={actionModal?.action === 'approve' ? 'success' : 'warning'}
              size="sm"
              onClick={confirmAction}
            >
              {actionModal?.action === 'approve' ? 'Confirm approval' : 'Confirm escalation'}
            </Button>
          </div>
        }
      >
        {actionModal && (
          <>
            <Alert type={actionModal.action === 'approve' ? 'success' : 'warning'}>
              {actionModal.action === 'approve'
                ? `You are approving ${actionModal.review.id} — ${actionModal.review.candidate}. This action will be logged with your reviewer ID and timestamp.`
                : `You are escalating ${actionModal.review.id} to a senior reviewer. The SLA clock continues.`
              }
            </Alert>
            <div style={{ marginTop: 14, fontSize: 13, color: '#64748B', lineHeight: 1.6 }}>
              <strong style={{ color: '#F8FAFC' }}>Reason:</strong> {actionModal.review.reason}
            </div>
          </>
        )}
      </Modal>
    </section>
  );
}
